### ISSUE TITLE
Scraper

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#320]
Competitor / Lists:
- [x] Fingerzeig
- [x] Programmzeitung
- [ ] http://barfi.ch/Events/Musik-Konzerte-Tanz
- [ ] http://gigs.gigatools.com/ (API: http://api.gigatools.com/)
- [ ] http://www.stadtkonzerte.ch/
- [ ] http://www.wherevent.com/search/Switzerland/Canton+of+Basel-City/Basel-City
- [ ] Baz/Eventbooster (?): [baz.ch](http://verlag.baz.ch/agenda/?date=04.12.2014&time=20&location=&category=D98DD764-D763-85BF-1B4EEABAA2D98809)
- [ ] http://www.eventrakete.ch/basel/
- [ ] http://allevents.in/basel/music

Facebook:
- [ ] https://www.facebook.com/J%C3%AAle-Caf%C3%A9-435642256522108/events
- [x] https://www.facebook.com/pages/OFF/187732204585769?sk=events
- [ ] https://www.facebook.com/sommercasino/events
- [x] https://www.facebook.com/BARAlpenblick/events
- [x] https://www.facebook.com/FassBar/events
- [ ] https://www.facebook.com/skuBAR.Basel/events
- [ ] https://www.facebook.com/irrsinn.barkleinbasel/events
- [ ] https://www.facebook.com/groups/52763837748/events/
- [ ] https://www.facebook.com/saali.zumgoldenenfass/events
- [ ] https://www.facebook.com/groups/46582560266/events/
- [x] https://www.facebook.com/pages/Kraftwerft-41/315712248445497?sk=events
- [ ] https://www.facebook.com/Dachbode/events
- [x] https://www.facebook.com/h95info/events
- [ ] https://www.facebook.com/caffebolognaunibas/events
- [x] https://www.facebook.com/wohnzimmerambahnhof/events
- [x] https://www.facebook.com/marina.basel/events
- [ ] https://www.facebook.com/NachbarsGartenBasel/events
- [ ] https://www.facebook.com/pages/Kaschemme-Basel/1514800852066390?sk=events
- [x] https://www.facebook.com/holzpark.klybeck/events
- [ ] https://www.facebook.com/Doors-Club-1228890980582838/events

Venues:
- [x] Kaschemme
- [x] Hinterhof
- [x] Sääli: http://www.goldenes-fass.ch/saali/
- [x] Alter Zoll: http://www.alterzoll.ch/
- [x] 8-bar http://www.8-bar.eu/events/
- [ ] Carambolage: http://www.carambolage.ch/carambolage/programm.html
- [x] [Elysia](http://elysia.ch/?page_id=277#dance)
- [ ] Nord*: http://nordstern.com/content/nordstern/de/programm.html
- [ ] Stadtcasino (off beat festival http://www.offbeat-concert.ch/) http://www.stadtcasino.ch/home.cfm
- [x] Z7 http://www.z-7.ch/
- [x] Apawi http://apawi.ch/events

**Comment by NicolasSchmutz** [comment]
@njam is it possible to grab a list of all venues with a facebook account to complete the description list?

**Comment by njam** [comment]
Good idea! Could you check which of these have events on facebook?
```
"id","name","url"
89,"Alpenblick","https://www.facebook.com/BARAlpenblick?fref=ts"
148,"Fassbar","http://www.facebook.com/FassBar"
170,"OFF","https://www.facebook.com/pages/OFF/187732204585769"
241,"Skubar","https://www.facebook.com/skuBAR.Basel"
268,"Irrsinn Bar","http://www.facebook.com/profile.php?id=100000893102865"
269,"Absturzbar","http://www.facebook.com/group.php?gid=52763837748"
271,"Sääli Zum Goldenen Fass","http://www.facebook.com/profile.php?id=100001520331555"
298,"Die Stube","http://www.facebook.com/Die.Stube"
300,"Silo83","http://www.facebook.com/group.php?gid=46582560266"
308,"100h Bar","http://www.facebook.com/100Stunden"
339,"Kraftwerft 41a","http://www.facebook.com/pages/Kraftwerft-41A/315712248445497"
341,"Technolounge","https://www.facebook.com/pages/Techno-lounge-Tanz-mitmir/125540097554010?sk=info"
357,"OstPol","https://www.facebook.com/events/396216353800355/?mall_view=posts"
384,"Dachbode","http://www.facebook.com/dachbode"
393,"H95 Raum für Kultur","http://www.facebook.com/h95info"
443,"Caffè Bologna","https://www.facebook.com/caffebolognaunibas"
464,"Velvet Club","https://www.facebook.com/VelvetClubBasel"
505,"Wohnzimmer am Bahnhof","https://www.facebook.com/wohnzimmerambahnhof"
523,"Marina","https://www.facebook.com/marina.basel"
524,"Nachbar's Garten","https://www.facebook.com/NachbarsGartenBasel"
544,"Sonnendeck","https://www.facebook.com/pages/Sonnendeck-nt-areal/110782959015299"
664,"Viu Eyewear","https://www.facebook.com/viueyewear"
687,"Crystal Palace","https://www.facebook.com/crystalpalacebasel"
699,"Stars Club Basel","https://www.facebook.com/starsbasel/info?tab=overview"
```

---
[1]
```
select id, name, url from `denkmal_model_venue` where url LIKE '%facebook%'
```

**Comment by NicolasSchmutz** [comment]
Okay, updated the description with all venues which have events on Facebook.

**Comment by NicolasSchmutz** [comment]
added Stadtcasino to description

**Comment by NicolasSchmutz** [comment]
@njam added http://www.stadtkonzerte.ch/

**Comment by NicolasSchmutz** [comment]
added most of it: https://github.com/denkmal/denkmal.org/issues/320#issuecomment-73013760
