### ISSUE TITLE
Fingerzeig scraper: Ignore certain genres

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#327]
related: https://github.com/denkmal/denkmal.org/issues/320

"tanz", "theater", "performance"
For example: http://fingerzeig.ch/parties/advsrch/?s=reithalle

We will ignore these events on the scraper level.
cc @NicolasSchmutz @frederickduerr

**Comment by NicolasSchmutz** [comment]
@njam is this done?

**Comment by NicolasSchmutz** [comment]
not relevant anymore
