### ISSUE TITLE
Select2 choice padding

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#331]
![screen shot 2014-11-22 at 13 08 21](https://cloud.githubusercontent.com/assets/360800/5154099/bef19668-7248-11e4-9f95-e2c3c5381d3c.png)

Two problems:
- Top padding is bigger than bottom padding (5px and 3px) - should it be the same?
- The "pseudo input" (`.select2-choices.textinput`) grows 1px in height once a "choice" is added.

Probably the two things are related, and might be fixable in CM?

**Comment by christopheschwyzer** [comment]
Fixed in https://github.com/cargomedia/cm/pull/2162
