### ISSUE TITLE
link tweets to twitter pages

### ISSUE THREAD

**Issue by frederickduerr** [denkmal/denkmal.org#340]
follow up of: https://github.com/denkmal/denkmal.org/pull/316

is it possible to link the tweets to the twitter pages of venues (if there is one) and maybe artists?

f.e:

instead of "Kaserne (23:00): Mind The Gap!: Mndsgn, Audio Dope, Johny Holiday, Reezm. Hiphop, electro"

"@KaserneBasel (23:00): Mind The Gap!: @mndsgn...."

**Comment by njam** [comment]
I've added a field "Twitter" for venues, which can be edited in the admin.
@NicolasSchmutz @frederickduerr do you wanna fill it out for all venues that are on twitter?

**Comment by NicolasSchmutz** [comment]
Sure will do.
@njam I assume it should be for example: `@KaserneBasel`

**Comment by njam** [comment]
Yes, with and without `@` will work.

**Comment by NicolasSchmutz** [comment]
@njam FYI
@frederickduerr added the venues which use twitter, although there are just a few (at the moment).

**Comment by njam** [comment]
These are set currently:
```
"Kaserne","KaserneBasel"
"Nordstern","nordsternbasel"
"Unternehmen Mitte","mitte_basel"
"Plattfon","plattfon"
"Hinterhof","hinterhof_ch"
"SUD","SUD_Basel"
"Hinterhof Dachterrasse","hinterhof_ch"
"Radio X","Radio_X_Basel"
"Conto 4056","Conto_4056"
```

**Comment by njam** [comment]
We should not put the twitter handle at the beginning of the tweet (in that case it would be considered a direct message to that account).
So how about this?:
> Today @KaserneBasel (22:00): Deep Afro House Night: Alma Negra, Féline.

Should we keep other venues, or also prefix them?:
> Kaschemme (22:00): Deep Afro House Night: Alma Negra, Féline.

> Today at Kaschemme (22:00): Deep Afro House Night: Alma Negra, Féline.

@NicolasSchmutz @frederickduerr wdyt?

**Comment by NicolasSchmutz** [comment]
Sgtm! I would keep the other venues to have some differentiation. 
Other ideas from @christopheschwyzer: https://github.com/denkmal/denkmal.org/pull/316#issuecomment-62368117

**Comment by njam** [comment]
How about:
- `Denkmal recommends: Nordstern (22:00): Foo bar denkmal.org/events?date=2014-10-31`
- `Denkmal recommends: @KaserneBasel (22:00): Foo bar denkmal.org/events?date=2014-10-31`

Or German?
- `Denkmal empfiehlt: Nordstern (22:00): Foo bar denkmal.org/events?date=2014-10-31`
- `Denkmal empfiehlt: @KaserneBasel (22:00): Foo bar denkmal.org/events?date=2014-10-31`

**Comment by NicolasSchmutz** [comment]
Okay I would go with:
- `Denkmal recommends: Nordstern (22:00) - Foo bar denkmal.org/events?date=2014-10-31`
- `Denkmal recommends: @KaserneBasel (22:00) - Foo bar denkmal.org/events?date=2014-10-31`
