### ISSUE TITLE
thumbnail on multitask manager iOS

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#350]
Why is there no picture/thumbnail in the iOS multitask manager for the Denkmal.org "Add to Homescreen" app?

![screen shot 2015-01-26 at 22 04 34](https://cloud.githubusercontent.com/assets/4020326/5908405/5ea4f812-a5a7-11e4-8451-a48bf5257a78.png)

**Comment by njam** [comment]
Did you try with other home screen apps?

**Comment by NicolasSchmutz** [comment]
Yes. 
I just found out that it works if Denkmal.org was the last opened site with Safari. 
Otherwise it's not visible anymore...

**Comment by njam** [comment]
This is most probably an iOS bug. This homescreen web-app feature is quite broken. Let's hope Google's focus on web apps makes Apple invest some more efforts in this area one day.
