### ISSUE TITLE
scroll doesn't work on FF 35.0.1

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#352]
Reported by Nathalie Geiser
FF 35.0.1, Mac OX 10.6.8

Update: She's using a trackpad.

**Comment by njam** [comment]
@nicolasschmutz can you check again - lots of JS dependencies udpated (fastclick) with new release

**Comment by NicolasSchmutz** [comment]
asked her...

**Comment by NicolasSchmutz** [comment]
This is a misunderstanding. Scrolling works actually but we don't have a scrollbar.
Told her to use scroll gesture.
