### ISSUE TITLE
Fasnacht Hackathon

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#353]
@NicolasSchmutz @christopheschwyzer @moby86

Ideas:
- Roveredo
- Wissifluh, Vitznau - http://www.wissifluh.ch/
- Pilgerhaus, Niederrickenbach - http://www.booking.com/hotel/ch/das-pilgerhaus.html

**Comment by NicolasSchmutz** [comment]
cc @frederickduerr

**Comment by moby86** [comment]
What dates were you thinking about?

**Comment by njam** [comment]
Maybe Saturday 21th - Wednesday 25th?

**Comment by NicolasSchmutz** [comment]
February right? 
Would be good for me!

**Comment by NicolasSchmutz** [comment]
btw: Wissifluh looks interesting!

**Comment by christopheschwyzer** [comment]
I'm up from Sunday. Also Schwarzwald could be an option. 
I'd prefer something not too far if possible. But ok with all options...

**Comment by njam** [comment]
Inquired at Wissifluh for 21.2. - 25.2.
Usually they're not open Mon-Tue, they will let me know whether they can host us.

**Comment by NicolasSchmutz** [comment]
@frederickduerr can't make it.
@njam any response from Wissifluh?

**Comment by njam** [comment]
Wissifluh is happy to have us!

Prices: 
- doppelt: 65
- einer: 80
- seilbahn: 12
- essen: 35
- seminar: 15

**Comment by NicolasSchmutz** [comment]
by what?

doppelt: 65/night
einer: 80/night
seilbahn: 12/ride
essen: 35/day
seminar: 15/day

**Comment by njam** [comment]
Exactly! :)

Should we go on February 21st? What time?

**Comment by NicolasSchmutz** [comment]
Cool, sgtm then!
So it's February 21. (Saturday) to 24. (Tuesday). I suggest to take the train at 10am.

**Comment by christopheschwyzer** [comment]
I will join on Sunday evening...

**Comment by njam** [comment]
@kris-lab let me know if you wanna join!

21.2. - 25.2. http://www.wissifluh.ch/

Prices:
- Double room: 65 / night
- Single room: 80 / night
- Gondola: 12 / ride
- Food: 35 / day
- Seminar: 15 / day

**Comment by kris-lab** [comment]
sure! I am very happy to join you:)

**Comment by njam** [comment]
I confirmed the stay with Wissifluh.
I told them we'd like single rooms. Please let me know if you prefer a different option!

**Comment by christopheschwyzer** [comment]
:+1:

**Comment by NicolasSchmutz** [comment]
huge success!
