### ISSUE TITLE
Release "Now"

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#413]
Plan:

**Step 1: Silent release on Saturday, 28. Feb**
- Find a bunch of hipsters before
- Enable anonymous access
- Start sharing on Saturday
- See how it goes, improve, fix, iterate..

**Step 2: Official release on Friday, 6. March**
- Possibly launch in a media-partnership with the Bscene festival
- Press release on relevant channels:
 - Watson
 - Vice
 - Tageswoche
 - Ronorp
 - BAZ
 - 20 Minuten

What do you think?

**Comment by vanillafudge** [comment]
20min

**Comment by vanillafudge** [comment]
It bothers me that I have to login everytime I'm visiting the page.

**Comment by christopheschwyzer** [comment]
:+1:

**Comment by NicolasSchmutz** [comment]
As discussed: I'll restrict the press release to just:
 - Vice
 - Tageswoche
 - Ron Orp

All the others don't really serve our audience. Denkmal is still kind of "underground" and that's what I, many users and organizer appreciate. We can also reach a lot with our Facebook and Twitter account.
I'll also call off Telebasel.

**Comment by NicolasSchmutz** [comment]
Added 20 min and Radio X after a discussion with Pat. ;)

**Comment by NicolasSchmutz** [comment]
[Press release](https://docs.google.com/document/d/15jeX5H-xnDLZy81YKnK_sxwNxdvB2msrze3h0LqWN1Q/edit?usp=sharing) sent to:
- Vice
- Zeitnah
- Tageswoche
- Ron Orp
- 20 min
- 20 min friday
- Radio X
- Radio Basilisk
- RFV
- 78s

**Comment by christopheschwyzer** [comment]
:+1:

**Comment by NicolasSchmutz** [comment]
confirmed until now:
- Bscene festival
- Ron Orp
- tbc

**Comment by njam** [comment]
:zap:
