### ISSUE TITLE
Pull-to-refresh

### ISSUE THREAD

**Issue by christopheschwyzer** [denkmal/denkmal.org#423]
On the Now page. 

Demo
http://cubiq.org/dropbox/iscroll4/examples/pull-to-refresh/

**Comment by NicolasSchmutz** [comment]
good idea!

**Comment by NicolasSchmutz** [comment]
After Bscene I have the feeling this is important and would be helpful.

**Comment by njam** [comment]
Let's close this because it's natively available in Chrome?

**Comment by christopheschwyzer** [comment]
agree
