### ISSUE TITLE
like button

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#437]
It would be great to have a like button or something similar to judge *denkmal now* posts.

**Comment by njam** [comment]
Thought about it many times too.
But I'm not 100% convinced yet. It makes the whole system more complicated - there would also need to be a way to spot *high rated* posts.

I would observe how the whole feed evolves for a few weeks/months, and then decide what should work differently and how we can accomplish it?

**Comment by NicolasSchmutz** [comment]
Agree. 
From my experience at BScence I (and also others) felt the need to like a post several times. :)

**Comment by njam** [comment]
Closing in favor of https://github.com/denkmal/denkmal.org/issues/438
