### ISSUE TITLE
improve Denkmal Now

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#438]
- input field: visible textfield without clicking on "T" icon
- location tracking: simplify search of privacy settings
- Interactivity: Like button
- User timeline: Allow to filter by user

**Comment by NicolasSchmutz** [comment]
should we open up photos for everyone (not just for hipsters)?

**Comment by njam** [comment]
That was done in https://github.com/denkmal/denkmal.org/pull/509 I think

**Comment by NicolasSchmutz** [comment]
ah true!  👍
