### ISSUE TITLE
pictures are warped

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#439]
![img_3087](https://cloud.githubusercontent.com/assets/4020326/6546616/f483f526-c5ba-11e4-969d-9e15be55285f.PNG)

**Comment by njam** [comment]
Do you know the camera these pictures were taken with?

**Comment by NicolasSchmutz** [comment]
iPhone 6 (landscape mode)

**Comment by njam** [comment]
Could you also link an original image file, so we can reproduce it

**Comment by NicolasSchmutz** [comment]
The picture was made on the site (Take Photo or Video) thus it wasn't saved.
But I have another example. Only the left side is cut off?
![img_3089](https://cloud.githubusercontent.com/assets/4020326/6551376/c78156f4-c637-11e4-87b4-27ee6b0fd4d0.JPG)

Original:
![img_3084](https://cloud.githubusercontent.com/assets/4020326/6551377/cc027898-c637-11e4-9e6c-c5f2717d1c83.JPG)

**Comment by alexispeter** [comment]
Should be fixed by https://github.com/cargomedia/CM/pull/1667
See comment https://github.com/cargomedia/CM/pull/1667#issuecomment-114896071 for details

**Comment by njam** [comment]
Done in https://github.com/denkmal/denkmal.org/pull/484
