### ISSUE TITLE
HeaderBar: Highlight current navigation item

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#440]
@christopheschwyzer I guess we should highlight all navigation item in the header-bar (triangle and brightness), like we do for the calendar:

![screen shot 2015-03-09 at 22 14 40](https://cloud.githubusercontent.com/assets/360800/6564532/c6fe5aac-c6a9-11e4-9bdc-b0e76413025f.png)
![screen shot 2015-03-09 at 22 14 54](https://cloud.githubusercontent.com/assets/360800/6564531/c6fd8c9e-c6a9-11e4-8712-83e4f61467ae.png)

**Comment by christopheschwyzer** [comment]
agree

**Comment by njam** [comment]
Closing in favor of https://github.com/denkmal/denkmal.org/pull/445
