### ISSUE TITLE
Marketing efforts - denkmal.org Basel / Graz

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#456]
Create business cards hipster / BSL GRZ:
includes unique code to create a denkmal hipster account.

**Comment by NicolasSchmutz** [comment]
idea: http://www.km-zuendholz.de/

**Comment by trampy** [comment]
Launch Event for Denkmal Graz

Technically possible, to promote it on Denkmal Basel?

Program:
- 2 DJs from Graz
- 2 DJs from Basel (any ideas/connections?)

Possible Location: http://www.postgarage.at

**Comment by trampy** [comment]
More ideas marketing:

- Matchboxes, with one side Basel, one side Graz. 5000 boxes around 500€.
http://streichhoelzer.de/produkte_details.php?pid=5&tmsid=2e0f41a0951d3079aaa6d8cb28a4dfa4

- Stickers, around 50-60€ for 1000 pcs. Either for each sub-brand (Basel or Graz), or combined.
http://www.flyeralarm.com/at/content/index/open/id/2800/aufkleber.html

**Comment by njam** [comment]
Facebook images for the launch party by Christophe:
- Graz: https://s3.amazonaws.com/uploads.hipchat.com/47729/321258/TJY3uTFbo0GSPjZ/facebook-launch-event-graz.png
- Basel: https://s3.amazonaws.com/uploads.hipchat.com/47729/321258/kk5AhswbGGLCiuX/facebook-launch-event-basel.png

**Comment by NicolasSchmutz** [comment]
Added budget to boost FB event: https://www.facebook.com/denkmal.org.basel/events
Added denkmal event: https://www.denkmal.org/basel/events?date=2016-10-14

**Comment by NicolasSchmutz** [comment]
todo:
- matchboxes: http://www.ihr-werbedruck.de/bedruckte-streichhoelzer-streichh1.php
- Press Releases

**Comment by NicolasSchmutz** [comment]
@christopheschwyzer reg. the matchboxes: I found the following site with a very fast delivery service: http://www.ihr-werbedruck.de/bedruckte-streichhoelzer-streichh1.php

We would like to order:
- 400 pcs.
- "Biggy Klein Schwarz"
- printed on both sides in "white"

front:
DENKMAL.ORG

back:
Owl eyes (from the night mode). Not sure if the nose is bright enough if we print it on black?

print template: http://www.ihr-werbedruck.de/vorlagen.php

Could you create it, send the template to info@ihr-werbedruck.de and ship the test example to LAS-Burg? I'll PM you my address.

**Comment by trampy** [comment]
Added budget to boost Graz-FB event: https://www.facebook.com/denkmal.org.graz/events
Added denkmal event: https://www.denkmal.org/graz/events?date=2016-10-14

@NicolasSchmutz: Will send you the press release on Tuesday, ok?

**Comment by NicolasSchmutz** [comment]
Matches were ordered.

**Comment by NicolasSchmutz** [comment]
@trampy I split up the press document into two. The link to share is: https://drive.google.com/drive/folders/0B-shhQygnohHSGRjcllsRFYwY3c

**Comment by NicolasSchmutz** [comment]
Press release for Basel was sent out to the following. LMK if you have other ideas!

www.programmzeitung.ch
www.bewegungsmelder.ch
www.tageswoche.ch
www.fingerzeig.ch
www.ronorp.net/basel
www.infam.antville.org
www.radiox.ch
www.barfi.ch
www.rfv.ch
www.20min.ch/schweiz/basel
www.friday-magazine.ch
www.telebasel.ch
www.basilisk.ch
www.stadtkonzerte.ch
www.eventrakete.ch

**Comment by NicolasSchmutz** [comment]
I'll pick up the matches tomorrow. 😐
