### ISSUE TITLE
venue can not have a comma

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#473]
new venue with comma gets the following error: `Too many elements.`

Not really a problem except: `Spiracles, LES` (Uferstrasse).

**Comment by njam** [comment]
When using which form? Admin? Which field are you filling out - "title"?

**Comment by NicolasSchmutz** [comment]
when adding a new venue: https://www.denkmal.org/add

**Comment by njam** [comment]
Ah *venue* - thanks for clarifying!

**Comment by NicolasSchmutz** [comment]
ah wrong description. changed it.

**Comment by njam** [comment]
Fixed in https://github.com/denkmal/denkmal.org/pull/484
