### ISSUE TITLE
admin event preview does not work anymore

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#479]
Normally there was a preview under the description once edited the event text.
@njam can you reproduce?

<img width="768" alt="screen shot 2015-07-10 at 09 21 01" src="https://cloud.githubusercontent.com/assets/4020326/8613952/12788700-26e5-11e5-91e9-83138c36d991.png">

**Comment by njam** [comment]
Fixed in https://github.com/denkmal/denkmal.org/pull/480
