### ISSUE TITLE
bug: landscape format picture

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#486]
landscape format is somehow strange and makes picture zoomed:

![upload](https://cloud.githubusercontent.com/assets/4020326/9185599/71988492-3fbd-11e5-9c68-ed70d6705609.png)

**Comment by njam** [comment]
Weird.
Chrome or Safari?
Do you know if it's the same on other sites?

**Comment by NicolasSchmutz** [comment]
Ah this only happens with the homescreen app but not with Safari.
Another one of these strange behaviours...

Closable?

**Comment by njam** [comment]
ok with me
