### ISSUE TITLE
Admin_Component_Event: Timezone inconstistency

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#494]
Editing an event in a different timezone than now (e.g. daylight saving) results in an offset of the stored date+time on the event.

cc @NicolasSchmutz

**Comment by njam** [comment]
Can't reproduce :|
Steps tried:
1. Current date is 2015-10-01 (Summer time)
2. Event date is 2015-11-01 (Winter time)
3. Change event time in admin -> Time is correctly saved.

**Comment by NicolasSchmutz** [comment]
As discussed maybe check the night of the switch to winter time (10-25-2015).

**Comment by njam** [comment]
Tried 2015-10-24, -25 and -26. Always AM and PM.
Can't reproduce…
