### ISSUE TITLE
Denkmal Graz

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#506]
Create a **Denkmal *sister site* for Graz**, Austria! Alex (@trampy) knows the city and will be responsible for the content.

<img src="https://cloud.githubusercontent.com/assets/360800/14580868/0ae3a3dc-03dd-11e6-8dad-4d6f3adff7ba.jpg" height=200>

Introduce a sister site:
- [x] Introduce a *region* concept (Basel, Graz)
 - [x] Add region model
 - [x] Add region to venue model https://github.com/denkmal/denkmal.org/pull/521
 - [x] Add region to ES indices, display events by region https://github.com/denkmal/denkmal.org/pull/558
- [x] Introduce two separate *sites*, associate each with a region
 - [x] Add link to regions selection page
- [x] Region selection
 - [x] Introduce a landing page on the generic site that redirects to a regional site based on the user's location (IP based?)
 - [x] Allow the user to select the region as a fallback https://github.com/denkmal/denkmal.org/pull/538
- [x] Admin: ability to edit events for a specific region
 - ~~Region-specific ACL for admins~~
 - Region-indication for other models
- [x] Check time zone logic https://github.com/denkmal/denkmal.org/pull/530
- [x] Twitter and email: https://github.com/denkmal/denkmal.org/issues/557
- [x] Denkmal_MessagePushNotification_SendJob https://github.com/denkmal/denkmal.org/pull/552
 - Add site to "push_subscription"
- [x]  API
- [x] Scraper: file structure, reporting
- [x] Suspension?
- [x] HTML comment
- [x] Enable Graz site
- [ ] launch-note banner on Denkmal Graz

Promote it:
- [x] Add content (venues, scrapers, events)
- [ ] Launch events
- [ ] Marketing/merchandise, together with Denkmal Basel? https://github.com/denkmal/denkmal.org/issues/456
- [x] Social media accounts?

**Comment by njam** [comment]
@NicolasSchmutz @trampy @christopheschwyzer @moby86 here's the Doodle for the hackathon:
http://doodle.com/poll/7ii9kiizshebicnb

**Comment by njam** [comment]
@denkmal/collaborators @fauvel @fvovan @ppp0 @vogdb @zazabe
We're planning to do a weekend-long hackathon for creating *Denkmal Graz*, a sister site of the event calendar for the city of Graz in Austria. Do you want to participate?
-> http://doodle.com/poll/7ii9kiizshebicnb

**Comment by trampy** [comment]
Perfect, thanks for the summary!

**Comment by njam** [comment]
It's a date! Please mark the weekend of **May 20th - 23th** in your calendar.

**Comment by njam** [comment]
Here's an idea:
We could go to this coworking space in Mulhouse: http://lespace-techdecom.com/
And sleep somewhere in Mulhouse, for example Hôtel de Bâle: http://www.hoteldebale.fr/

wdyt? I will ask if they would take guests on the weekend.

**Comment by NicolasSchmutz** [comment]
sgtm!
btw: I can only attend until Sunday afternoon

**Comment by trampy** [comment]
Hi Reto!
Thanks, sounds great!
Only one remark: Could we limit our stay to 3 days & 2 nights? (e.g. 20.-22.5.)
That would make it a bit easier for me (in terms of time and money).
Cheers,
Alex

**Comment by christopheschwyzer** [comment]
I know it's not the same, but I could also imagine doing a hackathon _light_ in Basel. This would certainly simplify things. Less costs, less trouble.

**Comment by njam** [comment]
I would prefer to go away, so I can fully focus on the project, but either works for me. It's also nice to get away ;)

I will visit the coworking space next Tuesday with Nicolas. They would rent us the place, and we can have the keys over weekend.
Of course everyone is free to stay as many days as they like.
Let's decide before Tuesday though!

**Comment by trampy** [comment]
Sounds all fine to me, thanks for organizing Reto! 
I would be definitely in from 20.-22.5, Basel or Mulhouse :)

Cheers,
Alex

**Comment by njam** [comment]
Ok great! We will visit the coworking next Tuesday, and then we can decide.

**Comment by NicolasSchmutz** [comment]
Other idea: http://www.kleinhafen.ch/

**Comment by njam** [comment]
Nicolas an I visited the co-working space in Mulhouse. The place is great, and the owners are nice. We could have the place for the weekend for ourselves. They will send us an offer next week.

If the price is reasonable I think we should do it. Will keep you posted.

<img src="https://cloud.githubusercontent.com/assets/360800/14998251/4fbfa5ce-1183-11e6-9612-38bc69857873.jpg" width=300>

**Comment by christopheschwyzer** [comment]
Cool. Looks good.

**Comment by njam** [comment]
Ok, we got a deal!
We will go to Mulhouse from 20.5. Friday afternoon until 22.5. Sunday evening.

Please book your own accommodation.
Nicolas, Christophe and me are staying at *Hotel de Bale*: http://www.booking.com/hotel/fr/de-bale.en-gb.html

**Comment by trampy** [comment]
Thanks a lot for organizing the co-working space!
Don’t know where I’m staying yet, but I will book this week.
Looking forward!

**Comment by trampy** [comment]
Hey! I’ll be staying at Residhotel Mulhouse, just 250m from your hotel.
http://bit.ly/1VW0tSK

Anyone knows if Timo is coming?

**Comment by NicolasSchmutz** [comment]
@moby86 are you joining as well?

**Comment by moby86** [comment]
Hey guys, I might join spontaneously for a day but would like to keep it open for now.

**Comment by NicolasSchmutz** [comment]
So far no answer from Marcel regarding the car. Should we go by Train?

**Comment by njam** [comment]
Ok sgtm. There are two possible connections:
- Basel SBB 14:21 -> Mulhouse Ville 14:44
- Basel SBB 15:21 -> Mulhouse Ville 15:44

Any preference?

**Comment by trampy** [comment]
Both would be fine for me :)

**Comment by njam** [comment]
Ok let's do
Basel SBB 14:21 -> Mulhouse Ville 14:44

The train departs from the *French* part of the railway station. Let's meet outside of the station at 14:30, then we have enough time to buy the tickets.

**Comment by njam** [comment]
Erm, let's meet 14:00!

**Comment by njam** [comment]
I updated the list of tasks in the ticket description. While it doesn't look like much, we in fact did some substantial groundwork!
I'm looking forward to launch Denkmal Graz!

**Comment by trampy** [comment]
I wanted to thank all of you - Reto, Nicolas, Christophe and Vladimir - for all your efforts during the weekend!
It was my first Hackathon, so I probably couldn’t contribute as much as you guys did, but I definitely got insight into the whole project.
Extremely looking forward to launch Denkmal Graz!

**Comment by NicolasSchmutz** [comment]
huge success! :stars:

**Comment by njam** [comment]
Backend changes are mostly finished.

@christopheschwyzer should we pair on the frontend changes? Maybe next weekend?

**Comment by christopheschwyzer** [comment]
sgtm

**Comment by njam** [comment]
Most of it is done! 💃 
Closing in favor of the milestone: https://github.com/denkmal/denkmal.org/milestone/1

**Comment by NicolasSchmutz** [comment]
:dizzy: 👏
