### ISSUE TITLE
[Meta] Overall UI improvements II

### ISSUE THREAD

**Issue by christopheschwyzer** [denkmal/denkmal.org#541]
- [ ] Images in Floatbox
- [ ] Now page
- [ ] EventList
- [x] Starred indication 
- [ ] Skyline footer
- [x] Replace "Basel" in translations
- [ ] click feedback

**Comment by trampy** [comment]
Got a feedback regarding the Denkmal-Now UI: The text and the photo-icon nearly look like stickers, so maybe those feaftures are often overlooked. 
Suggestion: Simply put those two icons in a separate row.
