### ISSUE TITLE
Denkmal Graz launch party

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#549]
Date: Fri, 2016-10-14

Ideas:
- [x] Event in Graz - Postgarage?
- [x] Event in Basel - Renée?
- [ ] Live multimedia mirror

@trampy iirc you mentioned to do the event at Postgarage? Do we need to book the venue now?

**Comment by NicolasSchmutz** [comment]
Something at Renée sgtm. I can organise it but first we need a date. @trampy when did you wanted to do it?

**Comment by trampy** [comment]
Thanks for bringing the topic up. I will contact the club in Graz next week to see which dates in October are available. Will let you know!

**Comment by NicolasSchmutz** [comment]
Idea: 
Set up two 360 cameras in both venues, live stream it over youtube and the visitors could check out the other party in VR:
- Gear 360: http://www.samsung.com/global/galaxy/gear-360/
- ALLie: https://allie.camera/
- Ricoh Theta: https://theta360.com/en/
- Sphericam: http://www.sphericam.com/
- Vuze: http://vuze.camera/product/vuze-vr-kit/
- Orah 4i: https://www.orah.co/

**Comment by njam** [comment]
@trampy could you talk to your guy at Postgarage?

**Comment by NicolasSchmutz** [comment]
https://docs.google.com/document/d/1SEe-nPphgF0uWyu2LLoLLcSIXfhdj5Vyj92YitHjDt8/edit#
