### ISSUE TITLE
adjust social media

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#553]
Twitter:
- [x] rename denkmal_org to denkmal_basel
- [x] create new account: denkmal_graz
- [x] create new facebook site denkmal_graz
- [x] add auto post form denkmal_graz twitter to fb

**Comment by NicolasSchmutz** [comment]
First three steps are done. @trampy I'll PM you the credentials for the twitter account.

I can't do the last step as my fb profile is already connected with https://twitter.com/denkmal_basel
@trampy can you do the last step: https://support.twitter.com/articles/31113

**Comment by trampy** [comment]
Twitter and Facebook page are now connected. Thanks for the pre-work!

FYI: I unpublished the FB-page for now, since there’s nothing on there yet.

Plus: Somehow I’m not 100% happy with the names of the Twitter & FB-accounts yet, but not sure what could be better ;)

**Comment by NicolasSchmutz** [comment]
>FYI: I unpublished the FB-page for now, since there’s nothing on there yet.

Thanks, makes sense.

>Plus: Somehow I’m not 100% happy with the names of the Twitter & FB-accounts yet, but not sure what could be better ;)

Agree it's a bit a mess also with upper case/lower case. Currently we have:

*Twitter*

Location | Username | Name
---|---|---
Basel | @denkmal_basel | Denkmal.org
Graz | @Denkmal_Graz | denkmal_graz

*Facebook*

Location | URL | Name
---|---|---
Basel | /denkmal.org | Denkmal.org
Graz | /denkmal.graz | Denkmal Graz


How About:

*Twitter*

Location | Username | Name
---|---|---
Basel | @denkmal_basel | Denkmal.org Basel
Graz | @denkmal_graz | Denkmal.org Graz


*Facebook*

Location | URL | Name
---|---|---
Basel | /denkmal.org.basel | Denkmal.org Basel
Graz | /denkmal.org.graz | Denkmal.org Graz

@njam wdyt?

**Comment by njam** [comment]
lgtm

**Comment by trampy** [comment]
I’ll make up my mind! Pretty busy this week, but we still have some time :)

**Comment by NicolasSchmutz** [comment]
sure, let me know...

**Comment by NicolasSchmutz** [comment]
@trampy lmk if I just adjust it like proposed: https://github.com/denkmal/denkmal.org/issues/553#issuecomment-225538304

**Comment by NicolasSchmutz** [comment]
Let's do:

### How About:

*Twitter*

Location | Username | Name
---|---|---
Basel | @denkmal_basel | Denkmal.org Basel
Graz | @denkmal_graz | Denkmal.org Graz


*Facebook*

Location | URL | Name
---|---|---
Basel | /denkmal.org.basel | Denkmal.org Basel
Graz | /denkmal.org.graz | Denkmal.org Graz

**Comment by NicolasSchmutz** [comment]
done
