### ISSUE TITLE
Regional email addresses

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#554]
Part of https://github.com/denkmal/denkmal.org/issues/506

**Comment by njam** [comment]
@NicolasSchmutz @trampy as discussed I set up email accounts "basel" and "graz", and for backwards compatibility redirected all generic ones to "basel":
![screen shot 2016-06-11 at 16 06 32](https://cloud.githubusercontent.com/assets/360800/15985478/ae8aac82-2fee-11e6-8514-b1e5b31d2e2d.png)

Please test if it works, and set up the email address as a new "sending address" in your email client.

**Comment by NicolasSchmutz** [comment]
The generic ones doesn't work. Rest lgtm.

Should I really set up a new "sending address" as kontakt@denkmal.org is very established?

**Comment by njam** [comment]
Oh ok, I changed it to forward directly to your Gmail account:
![screen shot 2016-06-11 at 21 31 31](https://cloud.githubusercontent.com/assets/360800/15987074/f552502a-301b-11e6-95d8-218005ef279c.png)

I thought we could slowly fade over to `basel@` by using it as the primary/reply-from address, while the old one still works. But that's up to you.

**Comment by njam** [comment]
Closing in favor of https://github.com/denkmal/denkmal.org/pull/557

@trampy please check if "graz@denkmal.org" works and is forwarded to you.

**Comment by trampy** [comment]
Works and is forwarded to me! Can you tell me how to set it up as a sending address?

**Comment by njam** [comment]
Are you using Gmail?
See: https://support.google.com/mail/answer/22370
and: http://webapps.stackexchange.com/questions/66228/add-new-alias-to-gmail-without-smtp-forwarding-only-address/72975#72975
