### ISSUE TITLE
Idea: Add label field

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#575]
> Idee für denkmal.org: Das Label der Acts hinzufügen falls vorhanden - das sagt oft sehr viel über was einem erwarten wird..

@moby86 thanks, do you have a example?

I assume most of the time we don't have the needed information for it.

**Comment by moby86** [comment]
Okay not so simple due to many labels listed and info not always available - but example: https://www.residentadvisor.net/dj/jeffmills

Maybe pick the one with highest number of "Members favourite"?
