### ISSUE TITLE
admin event-search doesn't work

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#576]
maybe relate to: https://github.com/denkmal/denkmal.org/issues/567

https://admin.denkmal.org/basel/events?searchTerm=Chang+Kee+Jazz

does it only work for future events?

**Comment by njam** [comment]
I forgot to re-create the ES index when setting up the new server. Fixed.

**Comment by NicolasSchmutz** [comment]
thanks!
