### ISSUE TITLE
Scraper Graz

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#579]
Part of https://github.com/denkmal/denkmal.org/issues/506

- [x] Facebook: venues
- [x] http://www.postgarage.at/Program.8.0.html
 - https://github.com/denkmal/denkmal.org/files/491248/Postgarage.txt
- [ ] Facebook: other pages
 - https://www.facebook.com/beatsupremeradio/events
 -https://www.facebook.com/MassivePlaygrounds/events
 -https://www.facebook.com/kopfbeifuss/events
 -https://www.facebook.com/HedonismusHacienda/events
 -https://www.facebook.com/frontrowlocos/events
- [x] http://subsubsub.at/

**Comment by trampy** [comment]
Postgarage Facebook-Scraper doesn't work somehow, maybe scraping the RSS-Feed is better...
[Postgarage.txt](https://github.com/denkmal/denkmal.org/files/491248/Postgarage.txt)

**Comment by trampy** [comment]
Venues, für die ein Facebook-Scraper eingetragen ist:

- Bunker
- Cuntra La Kunsthure
- Die Brücke
- Die Scherbe
- Dom im Berg
- Explosiv
- Feinkost Mild
- Forum Stadtpark
- Generalmusikdirektion
- Miles
- Orpheum
- p.p.c.
- Stockwerk

Veranstalter-Pages, über die auch ein Facebook-Scraper laufen könnte:

https://www.facebook.com/beatsupremeradio/events
https://www.facebook.com/MassivePlaygrounds/events
https://www.facebook.com/kopfbeifuss/events
https://www.facebook.com/HedonismusHacienda/events
https://www.facebook.com/frontrowlocos/events
https://www.facebook.com/ehrlichesbumbum/events
https://www.facebook.com/indiepartment/events
https://www.facebook.com/disko404/events
https://www.facebook.com/steirischerherbst/events

**Comment by njam** [comment]
@trampy you can now add those additional facebook pages to the "page list" scraper:
https://admin.denkmal.org/graz/scraper/facebook

Once that's done, I think we can close this ticket for now?

**Comment by trampy** [comment]
That’s awesome @njam <https://github.com/njam>! Thanks a lot for the work!

I just added 10 FB-pages and will let you know how it works.
