### ISSUE TITLE
Send email digest with events per week to venue-contact

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#58]
- [x] Add "email"-field to venue
- [ ] Populate email values (for most popular venues)
- [ ] Send weekly digest with list of upcoming events to these addresses (needs https://github.com/cargomedia/CM/issues/1257)
- [ ] Ability to propose changes to events

**Comment by NicolasSchmutz** [comment]
moved to https://gitlab.com/denkmal/denkmal-website/issues/4
