### ISSUE TITLE
Link to facebook event

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#580]
- Store the facebook event ID when scraping from facebook
- Link to the facebook event from the website

Depends on https://github.com/denkmal/denkmal.org/issues/641

**Comment by njam** [comment]
@NicolasSchmutz @trampy 
I'm now storing facebook links when an event is added through the facebook scraper (see https://github.com/denkmal/denkmal.org/pull/652). 
But if an event is added through another scraper, then we will not have the facebook link.
The order in which scrapers are processed is:
```
        return [
            new Denkmal_Scraper_Source_Kaschemme(),
            new Denkmal_Scraper_Source_Programmzeitung(),
            new Denkmal_Scraper_Source_Hinterhof(),
            new Denkmal_Scraper_Source_Fingerzeig(),
            new Denkmal_Scraper_Source_Saali(),
            new Denkmal_Scraper_Source_Apawi(),
            new Denkmal_Scraper_Source_Basel_Renee(),
            new Denkmal_Scraper_Source_Graz_Postgarage(),
            new Denkmal_Scraper_Source_Graz_Sub(),
            new Denkmal_Scraper_Source_Facebook_Venues(),
            new Denkmal_Scraper_Source_Facebook_PageList(),
        ];
```

Should we move facebook scrapers further to the top? I fear that the facebook event's quality is worse (e.g. very short event title).

Combining data from multiple scrapers is not so easy, because we can't know for sure which event in scraper A is the same event as in scraper B (because we allow for multiple events per day).

**Comment by NicolasSchmutz** [comment]
As discussed let's *not* move facebook scrapers further to the top as the quality of the other scraper in better.

**Comment by njam** [comment]
I've implemented it so that the scraper updates an existing event (to add additional facebook links), but *only* if there's only 1 event on that day (otherwise the heuristic to determine which event is the same doesn't work reliably). -> https://github.com/denkmal/denkmal.org/pull/653
