### ISSUE TITLE
Suggestion: Replace Label "Veranstaltung" with "Ort"

### ISSUE THREAD

**Issue by trampy** [denkmal/denkmal.org#582]
I find the labelling of the text fields a little bit misleading. Tempted to put the event name in the first field of the form: https://www.denkmal.org/basel/add
What do you think?

**Comment by njam** [comment]
The translation for "Venue" was set to "Veranstaltung". Changed it to "Ort".
I guess it was by accident @NicolasSchmutz ?

**Comment by NicolasSchmutz** [comment]
ah that explains a lot! so many venues with event titles in the last weeks....
