### ISSUE TITLE
Create GA views per region

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#585]
@NicolasSchmutz could you do it?

**Comment by NicolasSchmutz** [comment]
I changed the current view to `ALL denkmal.org` with no filter applied and created two copies of it with the following filters.

Basel only:
`Include only`  `traffic to the hostname`  `that contain`
https://www.denkmal.org/basel

Graz only:
`Include only`  `traffic to the hostname`  `that contain`
https://www.denkmal.org/graz

@njam I guess it should work like this?
"Referral Exclusion List" is probably not needed?

**Comment by njam** [comment]
lgtm
Let's check it in 24h to be sure

**Comment by NicolasSchmutz** [comment]
It does not work: https://analytics.google.com/analytics/web/?authuser=1#report/defaultid/a570541w958141p130447204/

I'm not sure what the problem is. It should work like we added it according to: http://www.ericmobley.net/guide-to-tracking-multiple-subdomains-in-google-analytics/

**Comment by njam** [comment]
I think the difference is that we need to filter by path/directory.

I updated both filters accordingly:
![screen shot 2016-09-29 at 09 39 00](https://cloud.githubusercontent.com/assets/360800/18944997/aa4df4cc-8628-11e6-8b30-9855da3ae0c0.png)

Let's verify again in 24h

**Comment by njam** [comment]
This didn't work because the URLs that are tracked in GA *do not contain* the region. A pageview for the events page in Graz (`/graz/events`) and one for the page in Basel (`/basel/events`) will both be tracked as `/events`. This is good because it allows to aggregate in the "ALL" view across all regions.

I've introduced a GA "custom dimension" called "region" which is set to "basel" or "graz" respectively. The filters are updated and the views seem to be tracking correctly now!
