### ISSUE TITLE
Denkmal Now Graz wrong GPS-Coordinates

### ISSUE THREAD

**Issue by trampy** [denkmal/denkmal.org#608]
Denkmal Now is currently not working in Graz due to wrong coordinates.
(Copied from the address bar of the browser using Google Maps. Apparently those coordinates are 150m from the real coordinates)

**Comment by NicolasSchmutz** [comment]
I use this page which is from my experience reliable: https://itouchmap.com/latlong.html

**Comment by trampy** [comment]
Thanks! I just entered the new coordinates using this website: http://www.gps-coordinates.net/
Will test in the next days and close the issue afterwards.
Do you know what's the radius for Denkmal now?

**Comment by NicolasSchmutz** [comment]
I can't remember exactly, @njam would need to look it up. Would guesstimate ~30m.

**Comment by trampy** [comment]
Thanks! I was just wondering since some venues are pretty large, others rather small. I guess the radius has to be a compromise.

**Comment by njam** [comment]
Are you sure the coordinates in the database (from Google Maps) are off and not the one that you measure with your phone?

The Location API returns an accuracy in meters, which we use as the radius. It will differ based on whether you have WiFi-based or GPS-based location information.

**Comment by trampy** [comment]
Resolved! It works now with the new coordinates! Sometimes I get locations to choose, which are pretty far away, but I think that's no big deal. Issue closed.
