### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by christopheschwyzer** [denkmal/denkmal.org#610]
…just so I don't forget!

**Comment by njam** [comment]
The `.meta.description` phrases are also quite important, and difficult to translate. Once we have a good translation I suggest we add them to a `fr.php`. See [`de.php`](https://github.com/denkmal/denkmal.org/blob/master/library/Denkmal/resources/translations/de.php) for reference:
```php
    $language->setTranslation('.meta.description', '{$siteName} wird von Locals gemacht. Entdecke das Nachtleben deiner Stadt, und finde heraus was jetzt gerade läuft.');
    $language->setTranslation('.meta.description.basel', 'Basels Eventkalender. WaslOift am Rheinknie und wie hört es sich an?');
    $language->setTranslation('.meta.description.graz', 'Events in Graz. Was geht in der Metropole an der Mur?');
```

**Comment by njam** [comment]
Closing in favor of https://github.com/denkmal/denkmal.org/issues/638
