### ISSUE TITLE
admin: improve show/hide button

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#622]
Currently it's not possible to edit a event, save it and simultaneously make it visible again.
The show button should also save the content.
@njam wdyt?

**Comment by njam** [comment]
Agree it's not so intuitive now.
Could also be a checkbox (like the "starred")?

I was also thinking about *autosave* for this form. But I think it's not a good idea, because one might want to edit the fields but then not save it. What do you think?

**Comment by NicolasSchmutz** [comment]
>Could also be a checkbox (like the "starred")?

sgtm, I wouldn't do autosave.
