### ISSUE TITLE
add google compatible location field

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#623]
moving from: https://github.com/denkmal/denkmal.org/issues/591#issuecomment-269336324

>I also noticed that the map link is just coordinates. Is it possible to get a "google" compatible location? See example:
![screen-shot-2016-12-27-at-15 53 42](https://cloud.githubusercontent.com/assets/1888817/21502014/0b7f9df8-cc4d-11e6-9bc8-979ab4d66d84.jpg)

I agree it would be better. We would probably need a new field in the admin to add something like this:

https://www.google.com/maps/place/REN%C3%89E/@47.5651241,7.5913044,16z/data=!4m5!3m4!1s0x0:0xbb23e687791a394!8m2!3d47.5625614!4d7.5913811

**Comment by njam** [comment]
I would not store a Google Maps link, as this information is not tied to a specific Maps provider and we might want to offer other choices in the future. But we should be able to pass long the venue-name to Google Maps as a search term.

- A: Current link: [https://www.google.com/maps/?q=47.5667,7.59242](https://www.google.com/maps/?q=47.5667,7.59242)
- B: With query. If no match found, it will show the coordinates without any marker: [https://www.google.com/maps/?ll=47.5667,7.59242&q=Terrorsamba](https://www.google.com/maps/?ll=47.5667,7.59242&q=Terrorsamba)
- C: With query (new format). If no match found it will look anywhere else (worldwide) and possibly show a wrong place not at the coordinates. [https://www.google.com/maps/search/Terrorsamba/@47.5667,7.59242](https://www.google.com/maps/search/Terrorsamba/@47.5667,7.59242)

I would go with B), wdyt?

There's also a [`geo:`-URL standard](https://en.wikipedia.org/wiki/Geo_URI_scheme), but it's not widely supported.

**Comment by NicolasSchmutz** [comment]
B sgtm!

**Comment by njam** [comment]
Unfortunately nothing works reliably the way we want it on Google maps :/
I'll go with B) now, as it seems to be the best compromise.

- A: https://www.google.com/maps?q=47.5657,7.59645
- B: https://www.google.com/maps?ll=47.5657,7.59645
- C: https://www.google.com/maps?ll=47.5657,7.59645&q=Nebel
- D: https://www.google.com/maps/search/Nebel/@47.5657,7.59645
- E: https://www.google.com/maps?q=Nebel%4047.5657,7.59645

**Comment by njam** [comment]
New plan:
 https://www.google.com/maps?q=Nebel@47.5657,7.59645
