### ISSUE TITLE
add ability to show events on renee.ch only

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#629]
Renée has more and more events which I don't really want to display on denkmal.org.
For example "Tartar Tuesday". It would be nice to have the ability to hide it on Denkmal but to display it on renee.ch. 
@njam wdyt?

**Comment by njam** [comment]
It might be better to set up a small CMS for Renée instead, so they can manage what shows up on their website themselves. This will allow them to have completely different content in the future if needed.
We can then scrape those events we want from the website :)
wdyt?

**Comment by njam** [comment]
I'm looking into the "Prismic.io" CMS here: https://github.com/renee-bar/renee-bar.github.io/issues/38

**Comment by NicolasSchmutz** [comment]
>It might be better to set up a small CMS for Renée instead, so they can manage what shows up on their website themselves. This will allow them to have completely different content in the future if needed.

Agree, that way it's more independent and you don't need to adjust opening hours.

**Comment by njam** [comment]
Closing this then
