### ISSUE TITLE
Renew SSL cert: *.denkmal.org

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#633]
Common Name
*.denkmal.org

Expiration Date
Apr 26 2017

Order Number
12440183

**Comment by NicolasSchmutz** [comment]
I bought it with a new account and moved it to puppet-cargomedia to renew SK site configuration: https://github.com/cargomedia/puppet-cargomedia/issues/1775

**Comment by njam** [comment]
deployed
![image](https://cloud.githubusercontent.com/assets/360800/23303062/1478efcc-fa92-11e6-9a65-108c26c29e01.png)
