### ISSUE TITLE
Remove French Language

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#638]

**Comment by christopheschwyzer** [comment]
oh :(

**Comment by njam** [comment]
We can easily re-add it! Since many phrases were not translated I thought it's better to remove it for the moment.

**Comment by christopheschwyzer** [comment]
😄 np. (I forgot to finish this) I check with Remo if he wants to do the translation on the hackathon weekend. Otherwise, agree, let's drop it.
