### ISSUE TITLE
Add Links to Event

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#641]
Allow admins to attach a list of links/urls to each event.
Links should have a label and a url.

Allow to enter a link through the "add" form.

**Comment by NicolasSchmutz** [comment]
@njam I noticed a small "issue": some user enter a "m.facebook.com/..." domain as event link. It will look weird on desktop. I guess we can't prevent them from doing it, especially if they enter it over a mobile. Maybe we should display a warning in the admin?

**Comment by njam** [comment]
@NicolasSchmutz can you post some example links?

**Comment by NicolasSchmutz** [comment]
Unfortunately not at the moment (I changed them). But in the picture you can see an example: https://github.com/denkmal/denkmal.org/issues/692 :/
