### ISSUE TITLE
New event-list design

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#643]
List entry includes:
- Venue name
- Event description
- Event time
- Indication if there's a song
- Tags (new functionality, see https://github.com/denkmal/denkmal.org/issues/640) (optional)
- Button to *favorite* the venue (new functionality, see https://github.com/denkmal/denkmal.org/issues/642) (optional)

On click event opens in large, with additional info:
- Song to play
- Map or link to map
- List of links for event (new functionality, see https://github.com/denkmal/denkmal.org/issues/641)
- Link to venue/location homepage

Design:
- venue and event description should be darker/ have more contrast

---

<img src="https://cloud.githubusercontent.com/assets/1888817/21501825/907c1a56-cc4b-11e6-8185-686be90dd654.png" width=200>

**Comment by NicolasSchmutz** [comment]
Second step/follow up when we have time:
Split up events text (title, acts, genre) in the admin to detect the different parts and design them differently.

**Comment by NicolasSchmutz** [comment]
The plan (details during dev)
![asdf](https://files.gitter.im/denkmal/denkmal.org/3VNJ/Screen-Shot-2017-02-24-at-18.10.33.png)

**Comment by christopheschwyzer** [comment]
done. closing.
