### ISSUE TITLE
Admin: improve floatbox

### ISSUE THREAD

**Issue by trampy** [denkmal/denkmal.org#670]
- [x] Add event day and date on top of or in the preview
- [ ] double event icon and music icon overlap
- [ ] no page break for long fb links
- [ ] genre and song should always be on the same line
- [ ] Automatically remove blanks on the beginning and on the end of the description before saving event 
- [ ] use floatbox for venues
- [ ] Detect related/similar events (https://github.com/denkmal/denkmal.org/issues/665)

**Comment by NicolasSchmutz** [comment]
>- [ ] Automatically remove blanks and dots from event description before saving the event

@trampy I would not remove dots completely but I agree blanks on the beginning or on the end of the description could be removed.

**Comment by NicolasSchmutz** [comment]
updated description

**Comment by NicolasSchmutz** [comment]
@christopheschwyzer there are a few minor issues in the admin caused by the new floatbox design + I have a few small ideas to further improve it (added to the description). Let me know when you have a moment to discuss it.

**Comment by NicolasSchmutz** [comment]
actually moved everything to https://github.com/denkmal/denkmal.org/issues/684
