### ISSUE TITLE
Force Upper/lower-case of genre text

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#671]
First letter uppercase, rest lowercase.

**Comment by njam** [comment]
All genres are currently written in lowercase (both in Basel and Graz).
For example:
![image](https://cloud.githubusercontent.com/assets/360800/26559428/d425e93a-44af-11e7-85ec-62bab6b08681.png)

In my opinion it looks better this way.

@NicolasSchmutz @trampy the idea of this ticket was to make the first letter of each genre uppercase. Do you still think we should do it?

**Comment by NicolasSchmutz** [comment]
I think this is a misunderstanding. The idea was to transform only the first character of *all* genres uppercase. It would be helpful for me if the rest would be transformed to lowercase automatically.

So basically if should look like it does now but done in a more automated way...

**Comment by trampy** [comment]
Agree with @NicolasSchmutz, an automatic lower-case transformation would be helpful.

**Comment by njam** [comment]
Ok got it:
> First letter uppercase, rest lowercase.
