### ISSUE TITLE
move addButton to footer

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#685]

**Comment by christopheschwyzer** [comment]
<img width="483" alt="screen shot 2017-03-05 at 00 52 58" src="https://cloud.githubusercontent.com/assets/1888817/23583231/44e3b748-013e-11e7-9fc4-8b2d18889bd2.png">

@NicolasSchmutz like this?

**Comment by christopheschwyzer** [comment]
The header bar will become a bit deserted when moving the "Add Event"-button. I think we should think about improving the design with this change.

To consider:
- Use the extra space to show location/date or a parts of it in the header bar so we can get rid of the one on top of the event list.
- Should we leave space for an audio play button to have global access to stop music from playing?
- …

I propose something like this:
![header-bar](https://cloud.githubusercontent.com/assets/1888817/23586724/668f3752-019b-11e7-80b9-402eeba11af7.jpg)

cc @NicolasSchmutz @njam

**Comment by njam** [comment]
I like it!
This way we could drop the full calendar date, and show it only in the overlay?
I would even consider making the "Add Event" just a link in the footer, instead of a button.

**Comment by NicolasSchmutz** [comment]
Cool! I like the second version "Sunday 23". Maybe even "Sunday 23.3."?

>This way we could drop the full calendar date, and show it only in the overlay?

Agree. let's drop it.

>I would even consider making the "Add Event" just a link in the footer, instead of a button.

Agree. On mobile I would do two footer lines:
- First: "Basel" / "Add Event"
- Second: "Twitter" / "Facebook"

**Comment by christopheschwyzer** [comment]
Current implementation:
![header-1](https://cloud.githubusercontent.com/assets/1888817/23590334/f9b16298-01dd-11e7-8dbd-bf7a8c9df3b0.jpg)

> Cool! I like the second version "Sunday 23". Maybe even "Sunday 23.3."?

Thought different solutions. I think to show only the day in the month is the most obvious (design and comprehensibility) If we have two numbers you start to wonder which one is month/day/year etc. 

> Agree. On mobile I would do two footer lines:

I tried it. Looks weird. My above solution is not perfect either… hm
<img width="405" alt="screen shot 2017-03-05 at 19 53 00" src="https://cloud.githubusercontent.com/assets/1888817/23590359/96c48a7e-01de-11e7-9e3e-8316f9948757.png">

**Comment by NicolasSchmutz** [comment]
>I tried it. Looks weird. My above solution is not perfect either… hm

Let's stick to your solution (one line)

**Comment by christopheschwyzer** [comment]
Made it a bit slicker even 
<img width="288" alt="screen shot 2017-03-06 at 17 48 04" src="https://cloud.githubusercontent.com/assets/1888817/23619800/19ccf56c-0295-11e7-8c2a-64b927b6824a.png">
