### ISSUE TITLE
Adjust "Event Link" text

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#695]
via: https://github.com/denkmal/denkmal.org/issues/641

>Allow to enter a link through the "add" form.

Let's adjust or extend the "Event Link" text on /add. Many user don't understand that it shouldn't be the blank link of the venue or a performers link. Also some start to add iTunes music links. :)

A good text which would solve this doesn't come to my mind at the moment. Any ideas?

**Comment by njam** [comment]
Should we just drop the field?
Or do you think it could be valuable to have the info?

**Comment by NicolasSchmutz** [comment]
I think it can be valuable. Some manage to add the right links. :)
I guess it's more about the description.

**Comment by NicolasSchmutz** [comment]
doen in https://github.com/denkmal/denkmal.org/pull/696
