### ISSUE TITLE
Event description cut off in floatbox

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#701]
![image](https://cloud.githubusercontent.com/assets/360800/23827231/1430db96-06af-11e7-9784-0b5cecbac254.png)

**Comment by christopheschwyzer** [comment]
@njam I assume this is resolved?

**Comment by njam** [comment]
Unfortunately not
I tried setting `flex-shrink: 0` to the middle `.event` element, which works. But then the wrapper element doesn' have all the flex-children combined's height, but only the height of the viewport. Thus the bottom of the floatbox doesn't have a white background.
Do you know how it can be done?
