### ISSUE TITLE
Loading screen appears after content

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#709]
Event text is visible before the loading screen appears.

[Untitled.mov.zip](https://github.com/denkmal/denkmal.org/files/850931/Untitled.mov.zip)

**Comment by njam** [comment]
@christopheschwyzer we should move `#loading` *above* `#middle` in `/layout/default/Layout/Default/default.tpl`. Otherwise it gets loaded and displayed after the content.
Could you try to move it? The positioning needs to be adjusted.
