### ISSUE TITLE
EventDetails: display placeholder for map during loading

### ISSUE THREAD

**Issue by njam** [denkmal/denkmal.org#715]
It looks strange if the spot for the map in the *event details* is just white while the map is loading.
How about we put some placeholder in the background, which is not preloaded, but the same for every event?

**Comment by christopheschwyzer** [comment]
Spinner?

**Comment by njam** [comment]
I think a moving spinner will be too disturbing and attracting attention.
I would rather use a static placeholder in light grey. Something very unobtrusive. Maybe just a solid grey background?
