### ISSUE TITLE
Adjust texts

### ISSUE THREAD

**Issue by christopheschwyzer** [denkmal/denkmal.org#723]
<img width="611" alt="screen shot 2017-03-17 at 23 16 32" src="https://cloud.githubusercontent.com/assets/1888817/24064974/10b3d58c-0b68-11e7-920a-d5073d536ad4.png">

- Rephrase and remove "impressions by the crowd in real-time".
- Same for meta description

**Comment by christopheschwyzer** [comment]
> Denkmal.org is an event calendar made and curated by locals. We help you explore your city's nightlife and make sure you never miss a great party again!

@NicolasSchmutz @njam wdyt? (open for suggestions. around 160chars would be good)

**Comment by NicolasSchmutz** [comment]
sgtm. @trampy any objections?

**Comment by njam** [comment]
Most users will see the German translation!
> Denkmal.org wird von Locals gemacht. Entdecke das Nachtleben deiner Stadt und verpasse keine erstklassige Party mehr!

**Comment by trampy** [comment]
Two small suggestions, but of course it's also fine the way it is :) 

Include "event" in the German text:
> Denkmal.org wird von Locals gemacht. Entdecke das Nachtleben deiner Stadt und verpasse keine ~~erstklassige Party~~ spannenden Events ~~mehr~~.

English:
> Denkmal.org is an event calendar made ~~and curated~~ by locals. Explore your city's nightlife and never miss a great party again.
