### ISSUE TITLE
Genre colour does not apply

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#724]
I added a few new genres (boogie and experimental) to the event-categories but I can't see the colour in the events: https://www.denkmal.org/basel/en/events?date=2017-3-18

Also only rock is underlined from "rock'n'roll" and r'n'r isn't although it's in the list. Has to be an issue with "'".

@njam could you check it before I add more genres?

**Comment by NicolasSchmutz** [comment]
>I added a few new genres (boogie and experimental) to the event-categories but I can't see the colour in the events: https://www.denkmal.org/basel/en/events?date=2017-3-18

It works if there is no space after the comma but not with a space:
<img width="216" alt="screen shot 2017-03-18 at 10 04 05" src="https://cloud.githubusercontent.com/assets/4020326/24070678/5e799004-0bc2-11e7-943f-e192c0dce90f.png">
<img width="259" alt="screen shot 2017-03-18 at 10 04 09" src="https://cloud.githubusercontent.com/assets/4020326/24070677/5e787e26-0bc2-11e7-85f8-55c7e18f3a26.png">

**Comment by NicolasSchmutz** [comment]
Thx!
This is still a issue:
>Also only rock is underlined from "rock'n'roll" and r'n'r isn't although it's in the list. Has to be an issue with "'".

Or is this only possible with: https://github.com/denkmal/denkmal.org/issues/671 ?

**Comment by njam** [comment]
There are different spellings in the event and in the genre:
```
rock’n’roll
rock'n'roll
```

**Comment by NicolasSchmutz** [comment]
I adjusted it but still have the problem. I guess it's because we also have "rock"?
<img width="175" alt="screen shot 2017-03-19 at 16 33 27" src="https://cloud.githubusercontent.com/assets/4020326/24082218/1d0f71b4-0cc2-11e7-9e2a-14eb88c71274.png">

**Comment by NicolasSchmutz** [comment]
It's also a problem for keys with two words like "heavy metal" where we also have "metal" as a single key. Both are handled in https://github.com/denkmal/denkmal.org/issues/671 ?
