### ISSUE TITLE
EventDetails: Venue name overlapping event date

### ISSUE THREAD

**Issue by trampy** [denkmal/denkmal.org#734]
I realized that the venue name is sometimes overlapping the event date. 
Suggestion: Display the event date one line above the venue title.
Wdyt @christopheschwyzer?

![img_1632](https://cloud.githubusercontent.com/assets/18462266/24206247/efb54adc-0f1d-11e7-849c-64ee59ef744f.PNG)

**Comment by NicolasSchmutz** [comment]
closing
