### ISSUE TITLE
EventDetails: Adjust labelling of venue and event links

### ISSUE THREAD

**Issue by trampy** [denkmal/denkmal.org#735]
The labelling of venue and event links can be a little bit confusing in my opinion.

Suggestion: Always name one link "Venue" and the other one "Event". Plus maybe introduce a venue icon, such as a house. Wdyt?

![img_1632](https://cloud.githubusercontent.com/assets/18462266/24206386/5dc21370-0f1e-11e7-87ad-5e4fd345eddd.PNG)

**Comment by njam** [comment]
"Veranstaltungsseite" - looks like a translation problem. Original in English is "Venue Website". A better translation could be "Veranstaltungsort"?
Or we could use the name of the venue as the link label - "Haus der Architektur"?

**Comment by NicolasSchmutz** [comment]
I changed it to "Veranstaltungsort" @trampy is that okay for you?

**Comment by trampy** [comment]
Thanks @NicolasSchmutz.
I also like @njam's idea, to display the name of the venue.

**Comment by NicolasSchmutz** [comment]
both versions are okay for me.

**Comment by njam** [comment]
I tested it again using the venue name as the link's label, but didn't like it. For many events the venue's name would appear twice within short distance.

I changed it to display the venue URL's *domain* instead (e.g. `postgarage.at`). I think it's easy to read and understand where it leads.
Let me know if you disagree, it's easy to revert.

**Comment by NicolasSchmutz** [comment]
cool!

**Comment by trampy** [comment]
Thanks, it definitely looks better this way! There's just one case where it looks strange: If a venue only has a Facebook-page, but no webpage:
<img width="485" alt="bildschirmfoto 2017-05-29 um 21 36 30" src="https://cloud.githubusercontent.com/assets/18462266/26560504/668b3148-44b7-11e7-84e7-53b10dc8bca1.png">

**Comment by njam** [comment]
Yes saw that too.
I'm not sure using a Facebook page as a homepage is a good idea in the first place ;)
I will add an exception so it shows the path after the domain too for facebook.
