### ISSUE TITLE
Add event form: Typo

### ISSUE THREAD

**Issue by trampy** [denkmal/denkmal.org#736]
Just stumbled upon one small typo in the add event form:

"Einen weitere**r** Event hinzufügen"

<img width="587" alt="bildschirmfoto 2017-03-22 um 16 45 07" src="https://cloud.githubusercontent.com/assets/18462266/24206639/29ea4ac6-0f1f-11e7-92e5-fcdefa58d0e9.png">

**Comment by NicolasSchmutz** [comment]
oh my bad. fixed
