### ISSUE TITLE
"Add Another Event" doesn't work anymore

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#755]
When adding another event in the form the time and the venue get stored but the following are removed: 
- Title
- Artists
- Genres
- Event Link

Or is it intentionally? If yes then I think we should change it and only remove "Event Link". wdyt?

**Comment by njam** [comment]
It was done like this on purpose, my assumption was that the submitter wants to add another event for the same venue. But most likely the event details (title, artists etc) will be different.

**Comment by NicolasSchmutz** [comment]
An inquirer asked for it because he wanted to add the same event on different dates.
But agree, both is possible. Let's ignore it....
