### ISSUE TITLE
Map images not loading anymore (403)

### ISSUE THREAD

**Issue by christopheschwyzer** [denkmal/denkmal.org#756]
> The Google Maps API server rejected your request. This API project was not found. This API project may have been deleted.

worked yesterday :/
@NicolasSchmutz @njam fyi

**Comment by njam** [comment]
Hm strange. I couldn't find the project where we created the key anymore. Created a new project and API key. Will invite you as collaborator.

**Comment by christopheschwyzer** [comment]
👍 thanks
