### ISSUE TITLE
Make denkmal.org financially sustainable

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#760]
In the long run I can't continue to maintain the content of the site on a daily basis but I'm still up to work on improvements and development. 

After several discussions I highly doubt that we can find someone who would maintain the content diligently, do it for a longer time, is not biased (from a venue or with only one specific genre interest) and would do the whole thing for free (b/c it's not their baby).

While I don't want to bury the project, I also don't think we can easily make a business out of it. I think we should find a solution to make it financially sustainable, so we could hire somebody (for example a student) how could maintain the content and in return would get something for it. Additionally (or maybe even first) it would be great to finance server costs, domain, certificate etc..

How much money would we need?
- Maintaining the content for /basel, adding new locations, emails (songs not included): Depending on the season ~1-2h/week = 8h/month * 20.-(?) = 160.-/month
- Maintenance costs: 400-500.-/year (@njam wdyt?)
=  max 2500.-/year

Idea:
I recently stumbled upon [Patreon](https://www.patreon.com/) and think this could be a good fit.
How about we do a small hackathon, create a video for it and spread our patreon on social media + on denkmal.org as a banner? Additionally we could go to the loactions we like and of course we could create flyers.  

@njam @christopheschwyzer @frederickduerr @fresswolf @moby86 wdyt?
@trampy I guess you could need something similar for Graz?

**Comment by christopheschwyzer** [comment]
Agree. I'd be willing to help with graphical assets creation. Maybe we should already look for someone and include her/him/them into the above proposed process already. (This way, she/he could get to know the team, share new ideas, be part from the "beginning"). How about we start an ad at unimarkt with something like "Enjoy Basels nightlife and get paid for it / Go out and get paid" 😄 Well, it doesn't have to be "clickbait", but could be funny imo.

**Comment by NicolasSchmutz** [comment]
great thanks and good idea!

btw we could also use denkmal.mit to present the project and raise money.

**Comment by njam** [comment]
Denkmal is currently hosted on an m4.large EC2 machine, which costs $73 per month. We could and should improve cost efficiency of the hosting in the future, but I want to wait a bit until we made some progress on dockerizing the PHP part at Cargo Media.

Another idea Nicolas and I talked about yesterday: how about we reach out to newspapers and other event agendas to discuss a possible collaboration/merger? Maybe there's an interesting opportunity somewhere for both sides, where they provide content and we provide the platform. For example Tageswoche, BaZ, Programmzeitung.

**Comment by christopheschwyzer** [comment]
sgtm

**Comment by NicolasSchmutz** [comment]
@ThomNagy as discussed over lunch please have a look and feel free to add your input. Also it would be great if you could make an intro with somebody from Tageswoche.

**Comment by trampy** [comment]
Hi everyone! My situation in Graz is kind of similar to Nicolas' situation in Basel as I'm also trying to find someone who helps me maintain the content. However, it's pretty difficult without any incentives. The attempt to get some funding via [Bürgerinnenbudget](https://xn--brgerinnenbudget-jzb.at/campaign.php?id=78) unfortunately failed. Another thought was to collaborate with certain clubs/venues who would provide permanent guestlists for Denkmal-admins as an incentive. What do you think about that @NicolasSchmutz? And of course it would be great to find some revenue streams to cover at least the server costs; I'm sorry that I couldn't contribute anything so far.

**Comment by NicolasSchmutz** [comment]
>Another thought was to collaborate with certain clubs/venues who would provide permanent guestlists for Denkmal-admins as an incentive. What do you think about that @NicolasSchmutz?

Also a good idea! @frederickduerr had a similar idea: we open up the member association, members would pay a member fee and in return they could win tickets provided by locations.

**Comment by NicolasSchmutz** [comment]
I didn't update for some time here. Reto, Christophe and I decided to announce publicly that we either need somebody who will take over the project or finance it. We'll release a banner on the page with the following questionnaire attached: https://goo.gl/forms/HZImIuNL6x6Z9wrU2

In addition I thought about reaching out to the following institutions in person (please let me know if you have other ideas):
- Programmzeitung
- Nachtstadtplan
- Fingerzeig
- Bscene
- JKF
- RFV
- Schappo
- CMS
- Tageswoche
- Facebook

**Comment by NicolasSchmutz** [comment]
--> http://www.20min.ch/schweiz/basel/story/15298447

**Comment by NicolasSchmutz** [comment]
closing for the moment
I'll continue to work on getting more passive member (mainly venues) into the association.
