### ISSUE TITLE
Fix Scraper "Sääli Zum Goldenen Fass"

### ISSUE THREAD

**Issue by NicolasSchmutz** [denkmal/denkmal.org#765]
The following is showing up in the admin as one event. @njam if you have some time could you look into it? No hurry though, For the moment, I re-added the events manually.

>DJ Salz Amixs lut Fr__02_03__21h___The Dead Brothers anschliessend: Reverend Sto: Sa__03_03__22h___Raunchy Rawhide Chicken 10 DJ, 100s of vinyl pearls EarlySoul, Funk, RnB, Rock`n`Roll, Country, Twanngy Stuff Do__08_03__22h___DJ S. Suurchrut Amixs guet Fr__09_03__22h___Cloak n Dagger Operation DJ John Eastwod dark n bright 80's Sa__10_03__22h____ DJ Whoopack & Kurtis Afro, Cumbia, Soul, Hip Hop Do__15_03__22h___Mirelle Mondieu Bunte Bete Fr__16_03__22h___Rumba Boxx Jalimann & Rootspro Calypso, Mento, Cumbia, Ska,... Sa_-17_03__22h___Guestbook DJana Mal schauen Mo__19_03__20h_

Site: http://www.goldenes-fass.ch/saali/

**Comment by njam** [comment]
That lovely Sääli website!
Unfortunately it's quite difficult currently to work on scrapers, because the development environment is not functional anymore (vagrant box etc). Could you do it manually for the next few months?

**Comment by NicolasSchmutz** [comment]
sure np

**Comment by NicolasSchmutz** [comment]
moved to gitlab: https://gitlab.com/denkmal/denkmal-website/issues/1
